language: node_js
node_js: stable
cache:
  directories:
    - node_modules
git:
  submodules: false
before_install:
  - git submodule update --init
install:
  - npm install
  - npm run validate
  - npm run format
  - npm run git-changed
script:
  - npm run bundle
  - npm run build
  - cd build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local-dir: build
  on:
    branch: master
    target_branch: gh-pages
  